apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-inventory
  namespace: argocd
spec:
  destination:
    namespace: inventory
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/Avatar1992/flask-inventory-devops.git'
    path: manifests
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
